import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';import {createCipheriv,randomBytes} from 'node:crypto';
const moduleSource=fs.readFileSync(new URL('../eufy_video_locks/back-cloud-control.mjs',import.meta.url),'utf8').replace(/^import .*from '@mega-yfue\/eufy-sdk';/m,'const SecureMqtt=undefined,buildAppShapedClientId=()=>"test-control",mqttUuidFrom=()=>"test";').replace("'./read-settings.mjs'",JSON.stringify(new URL('../eufy_video_locks/read-settings.mjs',import.meta.url).href));
const dynamicSource=moduleSource.replace("'./repair-config.mjs'",JSON.stringify(new URL('../eufy_video_locks/repair-config.mjs',import.meta.url).href));
const {installBackDoorCloudRoute,validateIdentity}=await import('data:text/javascript;base64,'+Buffer.from(dynamicSource).toString('base64'));
const sdk=fs.readFileSync((process.env.EUFY_TEST_SDK || new URL('../.test-sdk/package/dist/index.js',import.meta.url)),'utf8');const fn=name=>{const start=sdk.indexOf(`function ${name}(`);assert(start>=0);return sdk.slice(start,sdk.indexOf('\n}',start)+2);};const method=name=>{const start=sdk.search(new RegExp('^  (?:async )?'+name+'\\(','m'));assert(start>=0);return sdk.slice(start,sdk.indexOf('\n  }',start)+4).replaceAll('_MqttCommandRouter','Router');};
const ctx=vm.createContext({Buffer,Date,Math,setTimeout,clearTimeout,createCipheriv4:createCipheriv,randomBytes3:randomBytes,CMD_TRANSFER_PAYLOAD:1940,LOCK_COMMAND_CODE:{ON_OFF_LOCK:35},LOCK_API_COMMAND:{ON_OFF_LOCK:6018}});
vm.runInContext(['u16le','u16be','u32le','u32be','writeTlv','zeroPadToBlock','assembleFf09Frame','buildFf09Frame','ff09TransferPayload','toFf09Trans','buildFf09Trans','buildFf09MqttEnvelope','ff09MqttTopic'].map(fn).join('\n')+'\nclass Router {static FF09_ACK_TIMEOUT_MS=30;'+method('waitForMqttMessage')+'\n'+method('dispatchFf09Actuate')+'}\nthis.Router=Router;',ctx);
const identity={target:'T853100000000000',adminUserId:'0123456789abcdef0123456789abcdef01234567',cloudAccountId:'0123456789abcdef0123456789abcdef01234567',username:'Alice',shortUserId:'1234'};const userId='f'.repeat(40);const dev={sn:identity.target,model:'T8531',raw:{member:{admin_user_id:identity.adminUserId}}};
let sends=0,reads=0;let mode='good';let instances=[];let disconnects=0;
function replyFrame(time,status){const tail=Buffer.alloc(4);tail.writeUInt32BE(time);const iv=Buffer.from(identity.target);const c=createCipheriv('aes-128-cbc',Buffer.concat([Buffer.from(identity.adminUserId.slice(-12)),tail]),iv);const ct=Buffer.concat([c.update(Buffer.from([status&255])),c.final()]);const b=Buffer.concat([Buffer.from([255,9,0,0,3,0,2,0x48,35]),ct,Buffer.alloc(1)]);b.writeUInt16LE(b.length,2);b[b.length-1]=b.subarray(0,-1).reduce((a,v)=>a^v,0);return b.toString('hex');}
class Mqtt extends EventEmitter {constructor(options){super();this.options=options;instances.push(options.instanceIp);}id='test';async connect(){}async subscribe(topics){return topics;}async disconnect(){disconnects++;}async publish(topic,envelope){sends++;const raw=JSON.parse(envelope),payload=JSON.parse(raw.payload),trans=JSON.parse(Buffer.from(payload.trans,'base64'));assert.equal(payload.account_id,identity.cloudAccountId);assert.equal(trans.payload.apiCommand,6018);if(mode==='timeout')return;setImmediate(()=>{const build=time=>({topic:topic.replace('/req','/res'),raw:{head:{cmd:8,cmd_status:1},payload:JSON.stringify({trans:Buffer.from(JSON.stringify({cmd:1940,payload:{dev_sn:identity.target,time,lock_payload:replyFrame(time,mode==='reject'?-3:0)}})).toString('base64')})}});this.emit('message',build(trans.payload.time+1));this.emit('message',build(trans.payload.time));});}}
let originalCalls=0;const make=()=>{const router=new ctx.Router();router.deps={onCommandAck(){}};router.logger={debug(){}};router.deviceFor=async()=>dev;router.ensureSecurityMqttFor=async()=>{throw new Error('Original ensure should not serve target')};return {routeCommand:async()=>{originalCalls++;return'unchanged'},mqtt:router,mega:{auth:{userId},openudid:'private-install',getUserMqttInfo:async()=>({user_id:userId})},registry:{require:()=>dev}};};
const options={identity,Mqtt,lookup:async()=>['1.1.1.1','203.0.113.2'],reader:(_e,m)=>async()=>{reads++;if(m.options.instanceIp==='1.1.1.1'||mode==='no-settings')throw new Error('No settings reply');return{matchedReply:true,statusByte:0};}};
validateIdentity(identity,dev,userId);assert.throws(()=>validateIdentity({...identity,cloudAccountId:'unknown'},dev,userId));const eufy=make();installBackDoorCloudRoute(eufy,options);assert.equal(await eufy.routeCommand('front-door',{kind:'ff09-actuate'}),'unchanged');assert.equal(originalCalls,1);
for(const engage of [false,true]){await eufy.routeCommand(dev.sn,{kind:'ff09-actuate',engage,deviceSn:dev.sn});}
assert.equal(sends,2);assert.equal(reads,4);assert(instances.includes('203.0.113.2'));assert(disconnects>=4);
mode='reject';await assert.rejects(eufy.routeCommand(dev.sn,{kind:'ff09-actuate',engage:false,deviceSn:dev.sn}),/code -3/);
mode='no-settings';const before=sends;await assert.rejects(eufy.routeCommand(dev.sn,{kind:'ff09-actuate',engage:false,deviceSn:dev.sn}),/no actuator command sent/);assert.equal(sends,before);
mode='timeout';const hold=setInterval(()=>{},1000);try{await assert.rejects(eufy.routeCommand(dev.sn,{kind:'ff09-actuate',engage:false,deviceSn:dev.sn}),/response timed out/);}finally{clearInterval(hold);}

console.log('Passed: real SDK lock/unlock frames; current DNS candidates; validated GET before actuator; exact captured identity/direction; one publish; key-time correlation; nonzero response/timeout fail; no actuation if GET fails; readiness gate; unrelated devices unchanged.');
