import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {createS330Status,decodeS330LockState} from '../eufy_video_locks/s330-status.mjs';
for(const value of [undefined,null,'5',5,'0','',true,false,'03','4x',{},NaN]) assert.equal(decodeS330LockState(value),null);
for(const value of ['3',3]) assert.equal(decodeS330LockState(value),false);
for(const value of ['4',4]) assert.equal(decodeS330LockState(value),true);
const client=new EventEmitter();
const sn='T853000000000000';
const record={model:'T8530',stationSn:'T802100000000000',paramUpdatedAt:{1912:1700000000}};
client.registry={require:actual=>{assert.equal(actual,sn);return record}};
let time=1700000100500;
const apply=createS330Status(client,()=>time);
const dev={sn,model:'T8530',stationSn:'T802100000000000'};
assert.equal(apply(dev,{unknown_1912:'4'}).locked,true);
assert.equal(apply(dev,{unknown_1912:'3'}).locked,false);
assert.equal(apply(dev,{unknown_1912:'5'}).locked,null);
client.emit('lockState',{deviceSn:'other',locked:false});
client.emit('lockState',{deviceSn:sn,locked:'false'});
assert.equal(apply(dev,{unknown_1912:'4'}).locked,true);
client.emit('lockState',{deviceSn:sn,locked:false});
assert.equal(apply(dev,{unknown_1912:'4'}).locked,false); // stale cloud cannot undo push
assert.equal(apply(dev,{}).locked,false);
record.paramUpdatedAt[1912]=1700000101;
assert.equal(apply(dev,{unknown_1912:'4'}).locked,true); // newer real cloud timestamp can recover missed push
assert.equal(apply(dev,{unknown_1912:'5'}).locked,null);
time+=2000;client.emit('lockState',{deviceSn:sn,locked:true});
assert.equal(apply(dev,{unknown_1912:'3'}).locked,true);
record.paramUpdatedAt[1912]=undefined;
assert.equal(apply(dev,{unknown_1912:'3'}).locked,true);
assert.deepEqual(apply({sn:'other',model:'T8530'},{locked:false}),{locked:false});
assert.deepEqual(apply({sn,model:'T8531'},{locked:false}),{locked:false});
record.stationSn='other';assert.throws(()=>apply(dev,{}),/identity changed/);
console.log('S330 strict decoding, exact identity, live-event precedence and newer cloud recovery passed.');
import {mkdtempSync,mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,dirname} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {spawnSync} from 'node:child_process';
const fixture=mkdtempSync(join(tmpdir(),'s330-status-'));
mkdirSync(join(fixture,'src'));mkdirSync(join(fixture,'node_modules/@mega-yfue/eufy-sdk'),{recursive:true});
writeFileSync(join(fixture,'node_modules/@mega-yfue/eufy-sdk/package.json'),JSON.stringify({version:'0.3.0'}));
const here=dirname(fileURLToPath(import.meta.url));
writeFileSync(join(fixture,'src/device-view.mjs'),readFileSync(join(here,'fixtures/src/device-view.mjs')));
writeFileSync(join(fixture,'src/s330-status.mjs'),readFileSync(join(here,'../eufy_video_locks/s330-status.mjs')));
assert.equal(spawnSync(process.execPath,[join(here,'../eufy_video_locks/patch-status.mjs')],{env:{...process.env,BRIDGE_PATCH_ROOT:fixture}}).status,0);
assert.equal(spawnSync(process.execPath,['--check',join(fixture,'src/device-view.mjs')]).status,0);
const originalPatched=readFileSync(join(fixture,'src/device-view.mjs'),'utf8');
assert.notEqual(spawnSync(process.execPath,[join(here,'../eufy_video_locks/patch-status.mjs')],{env:{...process.env,BRIDGE_PATCH_ROOT:fixture}}).status,0);
assert.equal(readFileSync(join(fixture,'src/device-view.mjs'),'utf8'),originalPatched);
console.log('Guarded device-view build patch and syntax passed.');
